# 公共配置
config:
  tmp: D:\tmp
# HTTP监听
http-server:
  host: 0.0.0.0
  port: 8080
# 图片页面配置
image:
  client: stable-diffusion-cpp
  output: D:\tmp\lifuren\image
  clients:
    - stable-diffusion-cpp
    - paint-cycle-gan
    - paint-style-gan
# 诗词页面配置
poetry:
  client: poetize-shixian-rnn
  clients:
    - poetize-shimo-rnn
    - poetize-shifo-rnn
    - poetize-shigui-rnn
    - poetize-shixian-rnn
    - poetize-shisheng-rnn
    - poetize-lidu-rnn
    - poetize-suxin-rnn
    - poetize-wanyue-rnn
# 标记页面配置
mark:
  - path: D:\tmp\lifuren\mark\poetry
# RAG配置
rag:
  # faiss|elasticsearch
  type: elasticsearch
  size: 4
# 词嵌入配置
embedding:
  # ollama|chinese-word-vectors
  type: ollama
  # char|rhythm
  participle: rhythm
# Ollama配置
# https://github.com/ollama/ollama/blob/main/docs/api.md
ollama:
  api: http://192.168.8.228:11434
  username: 
  password: 
  # NONE|Basic|Token
  auth-type: NONE
  embedding:
    path: /api/embed
    model: quentinz/bge-large-zh-v1.5
    options: {}
# ElasticSearch配置
elasticsearch:
  api: http://192.168.8.183:9200
  username: elastic
  password: elastic
  # NONE|Basic|Token
  auth-type: Basic
# chinese-word-vectors配置
chinese-word-vectors:
  path: D:\tmp\lifuren\Chinese-Word-Vectors\sgns.sikuquanshu.word
# poetize-shifo-rnn配置
poetize-shifo-rnn:
  model: D:\tmp\lifuren\model\poetize-shifo-rnn.model
# poetize-shimo-rnn配置
poetize-shimo-rnn:
  model: D:\tmp\lifuren\model\poetize-shimo-rnn.model
# poetize-shigui-rnn配置
poetize-shigui-rnn:
  model: D:\tmp\lifuren\model\poetize-shigui-rnn.model
# poetize-shixian-rnn配置
poetize-shixian-rnn:
  model: D:\tmp\lifuren\model\poetize-shixian-rnn.model
# poetize-shisheng-rnn配置
poetize-shisheng-rnn:
  model: D:\tmp\lifuren\model\poetize-shisheng-rnn.model
# poetize-lidu-rnn配置
poetize-lidu-rnn:
  model: D:\tmp\lifuren\model\poetize-lidu-rnn.model
# poetize-suxin-rnn配置
poetize-suxin-rnn:
  model: D:\tmp\lifuren\model\poetize-suxin-rnn.model
# poetize-wanyue-rnn配置
poetize-wanyue-rnn:
  model: D:\tmp\lifuren\model\poetize-wanyue-rnn.model
# paint-cycle-gan配置
paint-cycle-gan:
  model: D:\tmp\lifuren\model\paint-cycle-gan.model
# paint-style-gan配置
paint-style-gan:
  model: D:\tmp\lifuren\model\paint-style-gan.model
# stable-diffusion-cpp配置
stable-diffusion-cpp:
  model: D:\tmp\lifuren\stable-diffusion-cpp\v1-5-pruned-emaonly.ckpt
  options: {}
  