# 公共配置
config:
  tmp: /tmp
# HTTP监听
http-server:
  host: 0.0.0.0
  port: 8080
# 音频页面配置
audio:
  path: /data/lifuren/audio
  client: compose-shikuang
  clients:
    - compose-shikuang
    - compose-liguinian
# 图片页面配置
image:
  path: /data/lifuren/image
  client: paint-wudaozi
  clients:
    - paint-wudaozi
    - paint-gukaizhi
# 图片页面配置
video:
  path: /data/lifuren/video
  client: act-guanhanqin
  clients:
    - act-guanhanqin
    - act-tangxianzu
# 诗词页面配置
poetry:
  path: /data/lifuren/poetry
  size: 768
  length: 4
  client: poetize-lidu
  clients:
    - poetize-lidu
    - poetize-suxin
# RAG配置
rag:
  # faiss|elasticsearch
  type: faiss
  size: 4
# ElasticSearch配置
elasticsearch:
  api: http://localhost:9200
  username: elastic
  password: elastic
  # NONE|Basic|Token
  auth-type: Basic
# 词嵌入配置
embedding:
  # ollama|pepper
  type: pepper
  # char|rhythm
  participle: rhythm
# Ollama配置
# https://github.com/ollama/ollama/blob/main/docs/api.md
ollama:
  api: http://localhost:11434
  dims: 768
  username: 
  password: 
  # NONE|Basic|Token
  auth-type: NONE
  embedding:
    path: /api/embed
    model: quentinz/bge-base-zh-v1.5
    # model: quentinz/bge-large-zh-v1.5
    # model: quentinz/bge-small-zh-v1.5
    options: {}
# pepper配置
pepper:
  dims: 768
  path: /data/lifuren/mark/poetry/.lifuren/pepper.word
  