# 公共配置
config:
  tmp: /tmp
# HTTP监听
http-server:
  host: 0.0.0.0
  port: 8080
# 音频页面配置
audio:
  path: /data/lifuren/audio
  model: 
  client: compose-shikuang
  clients:
    - compose-shikuang
    - compose-liguinian
# 图片页面配置
image:
  path: /data/lifuren/image
  model: 
  client: paint-wudaozi
  clients:
    - paint-wudaozi
    - paint-gukaizhi
# 图片页面配置
video:
  path: /data/lifuren/video
  model: 
  client: act-guanhanqing
  clients:
    - act-tangxianzu
    - act-guanhanqing
# 诗词页面配置
poetry:
  path: /data/lifuren/poetry
  model: 
  size: 768
  length: 4
  client: poetize-lidu
  clients:
    - poetize-lidu
    - poetize-suxin
  # 返回数量
  rag-size: 4
  # char|rhythm
  embedding-participle: rhythm
# ElasticSearch配置
elasticsearch:
  api: http://localhost:9200
  username: elastic
  password: elastic
  # NONE|Basic|Token
  auth-type: Basic
# Ollama配置
# https://github.com/ollama/ollama/blob/main/docs/api.md
ollama:
  api: http://localhost:11434
  dims: 768
  username: 
  password: 
  # NONE|Basic|Token
  auth-type: NONE
  embedding:
    path: /api/embed
    model: quentinz/bge-base-zh-v1.5
    # model: quentinz/bge-large-zh-v1.5
    # model: quentinz/bge-small-zh-v1.5
    options: {}
# pepper配置
pepper:
  dims: 768
  path: /data/lifuren/poetry/.lifuren/pepper.word
  