# HTTP监听
http-server:
  host: 0.0.0.0
  port: 8080
# 聊天页面配置
chat:
  client: ollama
  rag-size: 4
  clients:
    - ollama
    - openai
# 图片页面配置
image:
  client: stable-diffusion-cpp
  output: D:\tmp\data\image
  clients:
    - stable-diffusion-cpp
# 诗词页面配置
poetry:
# 图片标记页面配置
image-mark:
  - path: D:\tmp\data\mark\image
# 诗词标记页面配置
poetry-mark:
  - path: D:\tmp\data\mark\poetry
# 文档标记页面配置
document-mark:
  - rag: elasticsearch
    path: D:\tmp\data\mark\document
    chunk: LINE
    embedding: ollama
# OpenAI配置
openai:
  api:
  username:
  password:
  # NONE|Basic|Token
  auth-type: NONE
  chat:
    path: /v1/chat/completions
  embedding:
    path: /v1/embeddings
# Ollama配置
# https://github.com/ollama/ollama/blob/main/docs/api.md
ollama:
  api: http://192.168.8.228:11434
  username: 
  password: 
  # NONE|Basic|Token
  auth-type: NONE
  chat:
    path: /api/chat
    model: glm4
    top-p: 
    top-k:
    temperature: 
    options: {}
  embedding:
    path: /api/embed
    model: quentinz/bge-large-zh-v1.5
    options: {}
# stable-diffusion-cpp配置
stable-diffusion-cpp:
  model: D:\tmp\sdc\v1-5-pruned-emaonly.ckpt
  command: D:\tmp\sdc\sd.exe
  options: {}
# ElasticSearch配置
elasticsearch:
  api: http://192.168.8.183:9200
  username: elastic
  password: elastic
  # NONE|Basic|Token
  auth-type: Basic
  # RAG|TEXT
  embedding: TEXT
  