# 公共配置
config:
  tmp: D:\tmp
# 音频配置
audio:
  path: D:\tmp\lifuren\audio
  model: 
  client: audio-shikuang
  clients:
    - audio-shikuang
# 视频配置
video:
  path: D:\tmp\lifuren\video
  model: 
  client: video-wudaozi
  clients:
    - video-wudaozi
  