# 公共配置
config:
  tmp: /tmp
# 音频配置
audio:
  path: /data/lifuren/audio
  model: 
  client: audio-shikuang
  clients:
    - audio-shikuang
# 图片配置
video:
  path: /data/lifuren/video
  model: 
  client: video-wudaozi
  clients:
    - video-wudaozi
  