@baseUrl = http://localhost:8080

# @name 图片生成
POST {{baseUrl}}/image/generate HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0000

------WebKitFormBoundary0000
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< D:/tmp/image.jpg
------WebKitFormBoundary0000--

###
