@baseUrl = http://localhost:8080

# @name 视频生成
POST {{baseUrl}}/video/generate?model=video-wudaozi HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary0000

------WebKitFormBoundary0000
Content-Disposition: form-data; name="video"; filename="video.mp4"
Content-Type: video/mp4

< D:/tmp/video.mp4
------WebKitFormBoundary0000--

###
