name: build

on:
  push:
    branches: [ master ]

jobs:
  lifuren:
    name: Build lifuren
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout deps
        run: |
          git submodule update --init --recursive
          cd ./deps
          ################ glog
          cd ./glog
          git checkout v0.6.0
          cd ..
          ################ json
          cd ./json
          git checkout v3.11.2
          cd ..
          ################ fltk
          # sudo apt install libfltk1.3-dev=1.3.8-4
          sudo apt install libfltk1.3-dev
          ################ mlpack
          # sudo apt install libmlpack-dev
          sudo apt install libstb-dev libcereal-dev libarmadillo-dev libensmallen-dev
          git clone https://github.com/mlpack/mlpack.git
          cd mlpack
          git checkout 4.2.0
          mkdir build
          cd build
          cmake .. -D BUILD_CLI_EXECUTABLES=OFF
          sudo make -j 8 install
          cd ../../
          ################ opencv
          # sudo apt install libopencv-dev=4.5.4+dfsg-9ubuntu4
          sudo apt install libopencv-dev
          ################ libtorch
          wget  https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.0.1%2Bcpu.zip
          unzip libtorch-cxx11-abi-shared-with-deps-2.0.1+cpu.zip
      - name: Deploy lifuren
        run: |
          mkdir build
          cd build
          cmake ..
          make -j 8
          make clean
