name: build
on:
  push:
    branches: [ master ]
jobs:
  lifuren:
    name: Build lifuren
    # https://docs.github.com/zh/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout deps
        run: |
          git submodule update --init --recursive
          cd ./deps
          ################################ ppa
          # add-apt-repository
          # add-apt-repository -r
          # https://launchpad.net/ubuntu/+ppas
          sudo add-apt-repository -y ppa:leamas-alec/wxwidgets3.2
          sudo apt update
          ################################ opencv
          sudo  apt install libopencv-dev -y
          apt-cache madison libopencv-dev
          ################################ spdlog
          sudo  apt install libspdlog-dev -y
          apt-cache madison libspdlog-dev
          ################################ libtorch
          wget  https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.6.0%2Bcpu.zip > /dev/null 2>&1
          unzip libtorch-cxx11-abi-shared-with-deps-2.6.0+cpu.zip > /dev/null 2>&1
          ################################ wxWidgets
          sudo  apt install libgtk-3-dev libwxgtk3.2-dev libwxgtk-media3.2-dev -y
          apt-cache madison libgtk-3-dev libwxgtk3.2-dev libwxgtk-media3.2-dev
          # sudo  apt install libgtk-3-dev libwxgtk3.2-dev libwxgtk-media3.2-dev libwxgtk-webview3.2-dev -y
          # apt-cache madison libgtk-3-dev libwxgtk3.2-dev libwxgtk-media3.2-dev libwxgtk-webview3.2-dev
      - name: Deploy lifuren
        run: |
          gcc -v
          g++ -v
          cmake -version
          mkdir build ; cd $_
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make
          sudo make install
          make clean
