name: build

on:
  push:
    branches: [ master ]

jobs:
  lifuren:
    name: Build lifuren
    strategy:
      matrix:
        runs-on: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Mac Setting
        if: matrix.runs-on == 'macos-latest'
      - name: Linux Setting
        if: matrix.runs-on == 'ubuntu-latest'
      - name: Windows Setting
        if: matrix.runs-on == 'windows-latest'
        run: |
          echo "cmakeFlags=-G 'MinGW Makefiles'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout deps
        run: |
          git submodule update --init --recursive
          # glog
          cd ./deps/glog
          # git clone https://github.com/google/glog.git
          git checkout v0.6.0
          cd ..
          # pytorch
          git clone --recursive https://github.com/pytorch/pytorch.git
          cd pytorch
          git checkout v2.0.1
      - name: Build xx template
        run: |
          cd ./xx/template
          mkdir build
          cd build
          cmake ${{ env.cmakeFlags }} ..
          make
          make clean
      - name: Build xx glog
        run: |
          cd ./xx/glog
          mkdir build
          cd build
          cmake ${{ env.cmakeFlags }} ..
          make
          make clean
